### ISSUE TITLE
i586 support?

### ISSUE THREAD

**Issue by spvkgn** [cross-tools/musl-cross#7]
I tried the `x86_64-multilib-linux-musl` with `-m32 -march=i586` but it seems `-march` has no effect:

```
x86_64-multilib-linux-musl-gcc -o hello hello.c -m32 -march=i586 -static-libgcc -static

qemu-i386-static -cpu pentium hello
qemu: uncaught target signal 4 (Illegal instruction) - core dumped

qemu-i386-static -cpu pentium2 hello
qemu: uncaught target signal 4 (Illegal instruction) - core dumped

qemu-i386-static -cpu pentium3 hello
Hello, World!
```

**Comment by heiher** [comment]
Test building: https://github.com/musl-cross/musl-cross/actions/runs/11650031284

**Comment by heiher** [comment]
It's expected, as the `-march` option does not affect the prebuilt libraries. Adding the `i586` target is reasonable.
